[build]
  base    = "."
  command = "npm run build"
  publish = "template/dist"

[template.environment]
  NOTION_TOKEN = "Your Notion Integration Token"
  NOTION_DATASOURCE_ID = "Your Notion Data Source ID (posts collection)"
