[build]
  base    = "."
  command = "pnpm run build"
  publish = "templates/blog/dist"

[template.environment]
  NOTION_TOKEN = "Your Notion Integration Token"
  NOTION_DATASOURCE_ID = "Your Notion Data Source ID (posts collection)"
